USE cst;

DELETE FROM IBS.T1_VUCH_EMP_RELA
WHERE VUCH_NBR='DEPDEMO0001';

DELETE FROM IBS.T1_VUCH_DETAIL
WHERE VUCH_NBR='DEPDEMO0001';

INSERT INTO IBS.T1_VUCH_DETAIL
  (VUCH_NBR, VUCH_TYPE_ID, VUCH_TYPE_NM, WITH_CARD_F, CST_ID, CST_NM, ORG_ID, ORG_NM,
   BRANCH_ORG_NM, BRANCH_ORG_ID, OPEN_DT, CLOSE_DT, VUCH_STATUS_ID, VUCH_STATUS_NM,
   PROD_ID, PROD_NM, BIZ_TYPE_ID, BIZ_TYPE_NM, DEPT_ID, LN_AMT, MARKETING_NO, EMP_ID, CST_OPEN_DT)
SELECT
  'DEPDEMO0001', VUCH_TYPE_ID, VUCH_TYPE_NM, WITH_CARD_F, CST_ID, CST_NM, ORG_ID, ORG_NM,
  BRANCH_ORG_NM, BRANCH_ORG_ID, OPEN_DT, CLOSE_DT, VUCH_STATUS_ID, VUCH_STATUS_NM,
  PROD_ID, PROD_NM, 'SD',
  (SELECT BIZ_TYPE_NM FROM IBS.T9_BIZ_TYPE WHERE BIZ_TYPE_ID='SD' LIMIT 1),
  DEPT_ID, LN_AMT, NULL, 'admin', CST_OPEN_DT
FROM IBS.T1_VUCH_DETAIL
WHERE VUCH_NBR='QQDEMO0001';

INSERT INTO IBS.T1_VUCH_EMP_RELA
  (VUCH_NBR, EMP_ID, RATIO, CLAIM_STATUS_ID, CLAIM_DT, VERIFY_DT, VERIFY_EMP_ID, REMARK, REMARK1,
   ORG_ID, ORG_NM, CST_NM, BIZ_TYPE_NM, VUCH_STATUS_NM, OPEN_DT, EMP_NM, EMP_ORG_ID, EMP_ORG_NM,
   MARKETING_NO, FH_VERIFY_DT, FH_VERIFY_EMP_ID, CST_OPEN_DT, CST_ID, BIZ_TP_CD, BIZ_TP_NM, ST_LINE_TP_ID,
   PROD_ID, CTR_NBR, CTR_BAL, LN_DRDN_DT, LN_END_DT, LN_TP_ID, MIN_DRDN_DT_BY_CST, ADD_CST_FLAG, ADD_CTR_FLAG,
   ADD_FLAG, MNG_LINE_TP_ID, ACT_INT_INCM, ACR_INT_INCM, RISK_FLAG, RVS_EMP_ID, RVS_DT, RVS_CLAIM_EMP_ID,
   RVS_CLAIM_DT, RVS_RATIO, FH_VERIFY_EMP_NM, RVS_EMP_NM, RVS_CLAIM_EMP_NM, RVS_STATUS_ID)
SELECT
  'DEPDEMO0001', 'admin', 100.00, '0', CURDATE(), NULL, NULL, '', '',
  ORG_ID, ORG_NM, CST_NM,
  (SELECT BIZ_TYPE_NM FROM IBS.T9_BIZ_TYPE WHERE BIZ_TYPE_ID='SD' LIMIT 1),
  VUCH_STATUS_NM, OPEN_DT,
  (SELECT EMP_NM FROM IBS.T5_EMP WHERE EMP_ID='admin' LIMIT 1),
  (SELECT ORG_ID FROM IBS.T5_EMP WHERE EMP_ID='admin' LIMIT 1),
  (SELECT ORG_NM FROM IBS.T5_EMP WHERE EMP_ID='admin' LIMIT 1),
  NULL, NULL, NULL, CST_OPEN_DT, CST_ID, BIZ_TP_CD, BIZ_TP_NM, ST_LINE_TP_ID,
  PROD_ID, CTR_NBR, CTR_BAL, LN_DRDN_DT, LN_END_DT, LN_TP_ID, MIN_DRDN_DT_BY_CST, ADD_CST_FLAG, ADD_CTR_FLAG,
  ADD_FLAG, MNG_LINE_TP_ID, ACT_INT_INCM, ACR_INT_INCM, RISK_FLAG, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL
FROM IBS.T1_VUCH_EMP_RELA
WHERE VUCH_NBR='QQDEMO0001' AND EMP_ID='10001';
