USE cst;

DELETE FROM IBS.T1_VUCH_EMP_RELA
WHERE VUCH_NBR='DEPFHDEMO0001';

DELETE FROM IBS.T1_VUCH_DETAIL
WHERE VUCH_NBR='DEPFHDEMO0001';

INSERT INTO IBS.T1_VUCH_DETAIL
  (VUCH_NBR, VUCH_TYPE_ID, VUCH_TYPE_NM, WITH_CARD_F, CST_ID, CST_NM, ORG_ID, ORG_NM,
   BRANCH_ORG_NM, BRANCH_ORG_ID, OPEN_DT, CLOSE_DT, VUCH_STATUS_ID, VUCH_STATUS_NM,
   PROD_ID, PROD_NM, BIZ_TYPE_ID, BIZ_TYPE_NM, DEPT_ID, LN_AMT, MARKETING_NO, EMP_ID, CST_OPEN_DT)
SELECT
  'DEPFHDEMO0001', VUCH_TYPE_ID, VUCH_TYPE_NM, WITH_CARD_F, CST_ID, CST_NM, ORG_ID, ORG_NM,
  BRANCH_ORG_NM, BRANCH_ORG_ID, OPEN_DT, CLOSE_DT, VUCH_STATUS_ID, VUCH_STATUS_NM,
  PROD_ID, PROD_NM, 'SD',
  (SELECT BIZ_TYPE_NM FROM IBS.T9_BIZ_TYPE WHERE BIZ_TYPE_ID='SD' LIMIT 1),
  DEPT_ID, LN_AMT, NULL, 'admin', CST_OPEN_DT
FROM IBS.T1_VUCH_DETAIL
WHERE VUCH_NBR='QQDEMO0001';
