SET NAMES utf8mb4;

USE ibs;

UPDATE T1_VUCH_DETAIL
SET BIZ_TYPE_ID='CC',
    BIZ_TYPE_NM=(SELECT BIZ_TYPE_NM FROM T9_BIZ_TYPE WHERE BIZ_TYPE_ID='CC' LIMIT 1)
WHERE VUCH_NBR='LNDEMO0001'
  AND (COALESCE(BIZ_TYPE_NM,'')='' OR COALESCE(BIZ_TYPE_ID,'')<>'CC');
