CREATE DATABASE IF NOT EXISTS cst CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ibs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wabacus'@'%' IDENTIFIED BY 'wabacus';
GRANT ALL PRIVILEGES ON cst.* TO 'wabacus'@'%';
GRANT ALL PRIVILEGES ON ibs.* TO 'wabacus'@'%';
FLUSH PRIVILEGES;
